name: Release
on:
  push:
    branches:
      - main
    #tags:
    #  - "v*.*.*"

jobs:
  create_draft_release:
    #if: github.ref_type == 'tag'
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! gh release list | grep -q ${{ github.ref_name }}; then
            gh release create --title ${{ github.ref_name }} --draft ${{ github.ref_name }}
          fi

  linux_rocm:
    name: "x86_64-linux-gnu-${{ matrix.xla_target }}"
    needs: [create_draft_release]
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: false
          tool-cache: false
      - uses: actions/checkout@v3
      - name: Build XLA
        run: ./builds/build.sh rocm
      - name: Publish
        run: |
          ls "$(pwd)/builds/output/rocm/build"
          gh release upload --clobber ${{ github.ref_name }} "$(pwd)/builds/output/rocm/build/*/cache/build/xla_extension-x86_64-linux-gnu-rocm.tar.gz"
        env:
          GH_TOKEN: ${{ github.token }}
